Feature/issue14
12-venice/battleship pull request #39
Opened 2022-04-06 23:46 UTC by drzoiberg2005

Добавил валидацию формы, добавил страницу пользователя и страницу регистрации

2022-04-07 08:22 UTC, frontendkk1 reviewed
Спасибо за работу. Много Сделано. 
Есть небольшие замечания.

Которые не сохранились. FUCK

2022-04-07 08:26 UTC, frontendkk1 requested changes

2022-04-07 08:26 UTC, frontendkk1 commented on package.json
> +    "@types/materialize-css": "^1.0.11",
Давай зафиксируем версию. без шапочки

2022-04-07 10:01 UTC, realb0t commented on src/components/Button/Button.tsx
> +        // eslint-disable-next-line react/button-has-type
хорошей практикой будет отключать неугодные правило глобально

2022-04-07 10:16 UTC, frontendkk1 requested changes

2022-04-07 10:24 UTC, frontendkk1 commented on src/components/Button/Button.tsx
> +        // eslint-disable-next-line react/button-has-type
Считаю лучше писать над отключением причину. И если причина частая - менять правила или отключать их.

2022-04-07 10:53 UTC, frontendkk1 commented
Давай заголовок ПР как то опишем? а то непонятно о чем тут
<img width="545" alt="image" src="https://user-images.githubusercontent.com/99189116/162183400-c63a2711-a66c-4f8c-9020-b8b5d10da184.png">

2022-04-07 12:47 UTC, realb0t commented on src/components/Form/Form.tsx
> +            (obj, item) => Object.assign(obj, { [item.type]: '' }),
а почему бы не { ...obj, [item.type]: '' }

2022-04-07 12:47 UTC, realb0t commented on src/components/Form/Form.tsx
> +                            value={(form as any)[field.type]}
такие преобразования умножают на ноль весь тайпскрипт ) попробуй другой способ найти )

2022-04-07 12:49 UTC, realb0t commented on src/pages/RegisterPage/RegisterPage.tsx
> +    const fields = [
если это какой-то конфиг, то лучше его вынести из рендер-функции ) чтобы лучше читалось

2022-04-09 21:00 UTC, drzoiberg2005 commented on www/index.html
> +    <head>
Линтер подставил

2022-04-09 21:03 UTC, drzoiberg2005 commented on package.json
> +    "@types/materialize-css": "^1.0.11",
Исправил

2022-04-09 21:08 UTC, drzoiberg2005 commented on src/components/Button/Button.tsx
> +        // eslint-disable-next-line react/button-has-type
Исправил и указал причину

2022-04-09 21:09 UTC, drzoiberg2005 commented on src/components/Button/Button.tsx
> +        // eslint-disable-next-line react/button-has-type
Не получается, линтер все равно ругается

2022-04-09 21:09 UTC, drzoiberg2005 commented on src/components/Button/Button.tsx
> +        type={type || 'button'}
Исправил

2022-04-09 21:12 UTC, drzoiberg2005 commented on src/components/Button/Button.tsx
>          <span>{title.toUpperCase()}</span>
Убрал, но у нас все кнопки большими буквами, так что бы избежать ошибок с прописными буквами? по моему лучше было оставить

2022-04-09 21:14 UTC, drzoiberg2005 commented on src/components/Input/Input.tsx
> +import M from 'materialize-css';
Да
https://materializecss.com/text-inputs.html

2022-04-09 21:19 UTC, drzoiberg2005 commented on src/components/Input/validationFields.ts
> +            // eslint-disable-next-line no-useless-escape
Не получается

2022-04-09 21:20 UTC, drzoiberg2005 commented on src/pages/ProfilePage/ProfilePage.tsx
> +        phone: '89151437599',
Исправил

2022-04-09 21:21 UTC, drzoiberg2005 commented on src/pages/AuthPage/AuthPage.tsx
> +    // eslint-disable-next-line no-unused-vars
Не получается

2022-04-09 22:12 UTC, drzoiberg2005 commented on src/components/Form/Form.tsx
> +            (obj, item) => Object.assign(obj, { [item.type]: '' }),
Исправил

2022-04-09 22:12 UTC, drzoiberg2005 commented on src/components/Form/Form.tsx
> +                            value={(form as any)[field.type]}
Исправил

2022-04-09 22:13 UTC, drzoiberg2005 commented on src/pages/RegisterPage/RegisterPage.tsx
> +    // eslint-disable-next-line no-unused-vars
Это временное исключение пока не добавил API

2022-04-09 22:13 UTC, drzoiberg2005 commented on src/components/utils/ErrorBoundary/types.ts
>  export type ButtonProps = {
Исправил

2022-04-09 22:13 UTC, drzoiberg2005 commented on src/components/Form/Form.tsx
> +                            value={(form as any)[field.type]}
Исправил

2022-04-09 23:27 UTC, drzoiberg2005 commented on src/components/Form/Form.tsx
>                              key={index as any}
Исправил

2022-04-09 23:28 UTC, drzoiberg2005 commented on src/components/Form/Form.tsx
>                          <Input
А как можно упростить?

2022-04-09 23:29 UTC, drzoiberg2005 commented on src/components/Input/Input.tsx
> +    useEffect(() => {
Компонент отрисовывает в зависимости от валидации или что ты имеешь ввиду?

2022-04-09 23:30 UTC, drzoiberg2005 commented on src/pages/AuthPage/AuthPage.tsx
> +    // eslint-disable-next-line no-unused-vars
Исправил

2022-04-09 23:30 UTC, drzoiberg2005 commented on src/pages/RegisterPage/RegisterPage.tsx
> +    // eslint-disable-next-line no-unused-vars
Исправил

2022-04-09 23:30 UTC, drzoiberg2005 commented on src/pages/RegisterPage/RegisterPage.tsx
> +    const fields = [
Исправил

2022-04-10 20:24 UTC, frontendkk1 approved these changes

2022-04-10 20:26 UTC, RX-ON approved these changes

2022-04-10 20:26 UTC, merged